members_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.login_user, name="login_user"),
    path('logout', views.logout_user, name="logout_user"),
    path('signup', views.signup_user, name="signup_user"),
]

vacation_management_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('vacation_request', views.vacation_request, name="vacation_request"),
    path('all_requests', views.requests_list, name="requests_list"),
    path('all_users', views.users_list, name="users_list"),
]

vacation_management_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vacation_management_app.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('members_app.urls')),
]

vacation_management_app/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    user = models.OneToOneField(
        User, null=True, on_delete=models.CASCADE, verbose_name="Email")
    fullname = models.CharField(max_length=100, verbose_name="Full name")

    VIEWER = 'Viewer'
    EMPLOYEE = 'Employee'
    MANAGER = 'Manager'
    STATUS_CHOICES = [
        (VIEWER, 'Viewer'),
        (EMPLOYEE, 'Employee'),
        (MANAGER, 'Manager'),
    ]
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.user.email

    class Meta:
        verbose_name = "User Status"
        verbose_name_plural = "User Statuses"


class VacationRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account = models.ForeignKey(
        Account, on_delete=models.CASCADE, null=True, blank=True)
    start_date = models.DateField(verbose_name="Start date")
    finish_date = models.DateField(verbose_name="Finish date")
    # leave_type = models.ChoiceField(verbose_name="Leave Type")
    reason = models.TextField(
        max_length=1000, blank=True, verbose_name="Reason")

    CASUAL = 'Casual'
    MEDICAL = 'Medical'
    OPTIONAL = 'Optional'
    REGIONAL = 'Regional'
    LEAVE_CHOICES = [
        (CASUAL, 'Casual'),
        (MEDICAL, 'Medical'),
        (OPTIONAL, 'Optional'),
        (REGIONAL, 'Regional'),
    ]
    leave_type = models.CharField(
        max_length=10,
        choices=LEAVE_CHOICES,
        default=CASUAL,
    )

    WAITING = 'Waiting'
    APPROVED = 'Approved'
    REJECTED = 'Rejected'
    CANCELLED = 'Cancelled'
    STATUS_CHOICES = [
        (WAITING, 'Waiting'),
        (APPROVED, 'Approved'),
        (REJECTED, 'Rejected'),
        (CANCELLED, 'Cancelled'),
    ]
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default=WAITING,
    )

    class Meta:
        verbose_name = 'Leave Request'

    def __str__(self):
        return f"Vacation Request for {self.user.email}"

vacation_management_app/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import VacationRequest


class DatePickerInput(forms.DateInput):
    input_type = 'date'


class VacationRequestForm(forms.ModelForm):
    class Meta:
        model = VacationRequest
        fields = ['start_date', 'finish_date','leave_type', 'reason']
        widgets = {
            'start_date': DatePickerInput(),
            'finish_date': DatePickerInput(),
        }

    def clean_dates(self):
        start_date = self.cleaned_data['start_date']
        finish_date = self.cleaned_data['finish_date']
        if finish_date <= start_date:
            raise ValidationError(
                "Start date cannot be bigger than finish date")
        return start_date, finish_date

    def save(self, user, account, commit=True):
        vacation_request = VacationRequest.objects.create(
            user=user,
            start_date=self.cleaned_data['start_date'],
            finish_date=self.cleaned_data['finish_date'],
            leave_type=self.cleaned_data['leave_type'],
            reason=self.cleaned_data['reason'],
            account=account,
        )
        return vacation_request

vacation_management_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.db.models.query import QuerySet
from django.core.paginator import Paginator

from .decorators import status_validator
from .models import User, Account, VacationRequest
from .forms import VacationRequestForm

@login_required(login_url='login_user')
@status_validator
def home(request):
    user = get_object_or_404(User, pk=request.user.id)
    account = get_object_or_404(Account, user_id=request.user.id)
    if account.status is None:
        return render(request, 'vacation_management_app/no_permission.html')
    return render(request, 'vacation_management_app/home.html', {'user': user, 'account': account})


@login_required(login_url='login_user')
@status_validator
def vacation_request(request):
    form = VacationRequestForm(request.POST or None)
    account = get_object_or_404(Account, user_id=request.user.id)
    if account.status == Account.VIEWER:
        if request.method == "POST":
            messages.error(request, "Viewers are not allowed to send requests")
        return render(request, 'vacation_management_app/vacation_request.html', {'form': form, 'unavalaible': True})
    if request.method == "POST":
        if form.is_valid():
            try:
                form.clean_dates()
                form.save(user=request.user, account=account)
                messages.success(request, "Your request is submitted")
                return redirect('home')
            except ValidationError as e:
                messages.error(request, e.message)
        else:
            messages.error(request, "Something went wrong. Try again")
    return render(request, 'vacation_management_app/vacation_request.html', {'form': form})


@login_required(login_url='login_user')
@status_validator
def requests_list(request):
    statuses = {
        VacationRequest.WAITING: VacationRequest.WAITING,
        VacationRequest.APPROVED: VacationRequest.APPROVED,
        VacationRequest.REJECTED: VacationRequest.REJECTED,
        VacationRequest.CANCELLED: VacationRequest.CANCELLED,
    }
    leaveTypes = {
        VacationRequest.CASUAL: VacationRequest.CASUAL,
        VacationRequest.MEDICAL: VacationRequest.MEDICAL,
        VacationRequest.OPTIONAL: VacationRequest.OPTIONAL,
        VacationRequest.REGIONAL: VacationRequest.REGIONAL,
    }

    filtered_requests = QuerySet
    filtered_status = str()
    filtered_leaveType = str()
    if 'status' in request.GET:
        if request.GET['status'] in statuses.values():
            filtered_status = request.GET['status']
            filtered_requests = VacationRequest.objects.filter(
                user_id=request.user.id, status=filtered_status).order_by('-id')
    if 'leave_type' in request.GET:
        if request.GET['leave_type'] in leaveTypes.values():
            filtered_leaveType = request.GET['leave_type']
            filtered_requests = VacationRequest.objects.filter(
                user_id=request.user.id, leave_type=filtered_leaveType).order_by('-id')

    if filtered_requests == QuerySet:
        filtered_requests = VacationRequest.objects.filter(
            user_id=request.user.id).order_by('-id')
    amount_of_items = 3
    paginator = Paginator(filtered_requests, amount_of_items)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if page_number is None:
        page_number = 1
    requests = list(zip([x for x in range((amount_of_items * int(page_number)) -
                                          amount_of_items + 1, amount_of_items * int(page_number) + 1)], page_obj))
    return render(request, 'vacation_management_app/requests_list.html', {'requests': requests, 'statuses': statuses, 'leaveTypes': leaveTypes, 'page_obj': page_obj, 'filtered_status': filtered_status, 'filtered_leaveType': filtered_leaveType})


@login_required(login_url='login_user')
@status_validator
def users_list(request):
    users =  User.objects.all().values()
    print(">>>>>>>>>>>>>")
    print(User.objects.all().values())
    return render(user, 'vacation_management_app/users_list.html',{'users': users})

vacation_management_app/templates/vacation_management_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Leave Management App</title>
    <style>
        html, body {
            height: 97%;
        }
        .container {
            max-width: 960px;
        }
    </style>
</head>
<body>
    <!-- NavBar -->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container d-flex">
            <a class="navbar-brand" href="{% url 'home' %}">Leave Management</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"data-bs-target="#navbarSupportedContent"aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Togglenavigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            {% if user.is_authenticated %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="me-auto"></div>
                <a href="{% url 'logout_user' %}"><button class="btn btn-outline-success" type="submit">Logout</button></a>
            </div>
            {% else %}
            {% if login %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="me-auto"></div>
                <a href="{% url 'signup_user' %}"><button class="btn btn-outline-success" type="submit">Sign Up</button></a>
            </div>
            {% elif signup %}
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="me-auto"></div>
                <a href="{% url 'login_user' %}"><button class="btn btn-outline-success" type="submit">Login</button></a>
            </div>
            {% endif %}
            {% endif %}
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

vacation_management_app/templates/vacation_management_app/home.html
{% extends 'vacation_management_app/base.html' %}
{% block content %}
<div class="container d-flex flex-column justify-content-center align-items-center" style="height: inherit;">
    <div class="col-sm-6">{% include 'vacation_management_app/messages.html' %}</div>
    <h1 class="mb-2 text-center">Hello, {{ account.fullname }}</h1>
    <p class="fs-5 text-center">Your current status is <b>{{ account.get_status_display }}</b></p>
    <a href="{% url 'vacation_request' %}"><button type="button" class="btn btn-primary mb-2">New Leave Request</button></a>
    <a href="{% url 'requests_list' %}"><button type="button" class="btn btn-success mb-5">All Requests</button></a>
    <!-- <a href="{% url 'users_list' %}"><button type="button" class="btn btn-success mb-5">All Users</button></a> -->
</div>
{% endblock content %}

vacation_management_app/templates/vacation_management_app/messages.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}success{% endif %} alert-dismissible fade show" role="alert">
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}<strong>Error!</strong>{% endif %} {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}

vacation_management_app/templates/vacation_management_app/no_permission.html
{% extends 'vacation_management_app/base.html' %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center flex-column" style="height: inherit;">
    <div class="alert alert-danger mb-4" role="alert">
        <h4 class="alert-heading">No permission!</h4>
        <p>At the moment you do not have permission to see this page unless our administrators give it to you.</p>
        <hr>
        <p class="mb-0">All what you need is just wait for the decision.</p>
    </div>
</div>
{% endblock content %}

vacation_management_app/templates/vacation_management_app/requests_list.html
{% extends 'vacation_management_app/base.html' %}
{% block content %}
<style>
  .parent {
  margin: 1rem;
  padding: 2rem 2rem;
  text-align: center;
}
.child {
  display: inline-block;
  padding: 1rem 1rem;
  vertical-align: middle;
}
</style>
<div class="container mt-5 pb-2">
    {% if not requests and not filtered_status %}
    <div class="justify-content-center d-flex flex-column">
        <h1 class="text-center">You don't have any requests</h1>
        <a class="fs-5 text-center" href="{% url 'home' %}" style="text-decoration: none;">Home</a>
    </div>
    {% else %}
    <div class="d-flex justify-content-cetner align-items-center flex-column mb-5">
        <h1 class="text-center">Requested history</h1>

        <div class='parent'>
          <div class='child'><div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Filter Status
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?status={{ statuses.Waiting }}">Waiting</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?status={{ statuses.Approved }}">Approved</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?status={{ statuses.Rejected }}">Rejected</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?status={{ statuses.Cancelled }}">Cancelled</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}">Clear filter</a></li>
            </ul>
        </div></div>
          <div class='child'><div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Filter Leave Type
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?leave_type={{ leaveTypes.Casual }}">Casual</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?leave_type={{ leaveTypes.Medical }}">Medical</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?leave_type={{ leaveTypes.Optional }}">Optional</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?leave_type={{ leaveTypes.Regional }}">Regional</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}">Clear filter</a></li>
            </ul>
        </div></div>
        </div>        
    </div>
    {% if not requests %}<h2 class="fw-normal text-center">There are no requests of <b>{{ filtered_status }}</b> status</h2>{% endif %}
    {% endif %}
    {% if requests %}
    {% for index, request in requests %}
    <div class="mb-3">
        <div class="list-group list-group-light">
            <h2 class="mb-2">Request {{ index }}{% if request.reason %}, <span class="fw-normal">{{ request.reason|truncatechars:40 }}</span>{% endif %}</h2>
            <div class="list-group-item list-group-item-action px-3 border-0 rounded-3 mb-2 list-group-item-secondary d-flex justify-content-between align-items-start" data-bs-toggle="modal" data-bs-target="#modal{{ request.id }}" style="cursor: pointer;">
                <div class="me-auto">{{ request.start_date|date:'j.m.Y' }} - {{ request.finish_date|date:'j.m.Y' }}</div>
                <div class="mx-auto" style="width: 200px;"><h6>{{ request.leave_type }}</h6></div>
                <span class="badge text-bg-{% if request.status == statuses.Waiting %}primary{% elif request.status == statuses.Approved %}success{% else %}danger{% endif %}">{{ request.get_status_display }}</span>
              
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    {% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="pb-3 pt-2">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% endif %}
          {% for p in page_obj.paginator.page_range %}
          {% if page_obj.number == p %}
          <li class="page-item"><a class="page-link active" href="?page={{ p }}">{{ p }}</a></li>
          {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
          <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
          {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
<!-- Modal -->
{% for index, request in requests %}
<div class="modal fade" id="modal{{ request.id }}" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="ModalLabel">Request {{ index }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body border">
        <b>From:</b> {{ request.start_date|date:'F d, Y' }}<br>
        <b>Till:</b> {{ request.finish_date|date:'F d, Y' }}<br>
        <b>Leave Type:</b> {{ request.leave_type }}<br>
        <b>Reason:</b> <br>{% if request.reason %}{{ request.reason }}<br>{% endif %}
        <span class="badge text-bg-{% if request.status == statuses.Waiting %}primary{% elif request.status == statuses.Approved %}success{% else %}danger{% endif %}">{{ request.get_status_display }}</span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Got it</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% endblock content %}

vacation_management_app/templates/vacation_management_app/users_list.html
{% extends 'vacation_management_app/base.html' %}
{% block content %}
<style>
  .parent {
  margin: 1rem;
  padding: 2rem 2rem;
  text-align: center;
}
.child {
  display: inline-block;
  padding: 1rem 1rem;
  vertical-align: middle;
}
</style>
<div class="container mt-5 pb-2">
    {% if not users %}
    <div class="justify-content-center d-flex flex-column">
        <h1 class="text-center">You don't have any requests</h1>
        <a class="fs-5 text-center" href="{% url 'home' %}" style="text-decoration: none;">Home</a>
    </div>
    {% else %}
    <div class="d-flex justify-content-cetner align-items-center flex-column mb-5">
        <h1 class="text-center">User Lists </h1>

        <!-- <div class='parent'>
          <div class='child'><div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Filter Status
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?status={{ statuses.Waiting }}">Waiting</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?status={{ statuses.Approved }}">Approved</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?status={{ statuses.Rejected }}">Rejected</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?status={{ statuses.Cancelled }}">Cancelled</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}">Clear filter</a></li>
            </ul>
        </div></div>
          <div class='child'><div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Filter Leave Type
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?leave_type={{ leaveTypes.Casual }}">Casual</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?leave_type={{ leaveTypes.Medical }}">Medical</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?leave_type={{ leaveTypes.Optional }}">Optional</a></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}?leave_type={{ leaveTypes.Regional }}">Regional</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'requests_list' %}">Clear filter</a></li>
            </ul>
        </div></div>
        </div>  -->
    </div>
    <!-- {% if not users %}<h2 class="fw-normal text-center">There are no requests of <b>{{ filtered_status }}</b> status</h2>{% endif %} -->
   {% endif %} 
    {% if users %} 
    {% for index, user in users %}
    <div class="me-auto">{{ user.username }}</div>
    <!-- <div class="mb-3">
        <div class="list-group list-group-light">
            <h2 class="mb-2">Request {{ index }}{% if user.username %}, <span class="fw-normal">{{ user.username|truncatechars:40 }}</span>{% endif %}</h2>
            <div class="list-group-item list-group-item-action px-3 border-0 rounded-3 mb-2 list-group-item-secondary d-flex justify-content-between align-items-start" data-bs-toggle="modal" data-bs-target="#modal{{ user.id }}" style="cursor: pointer;">
                <div class="me-auto">{{ user.date_joined|date:'j.m.Y' }}</div>
                <div class="mx-auto" style="width: 200px;"><h6>{{ user.is_staff }}</h6></div>
                <span class="badge text-bg-{% if user.is_active == 'Active' %}primary{% elif user.is_active == 'inactive' %}success{% else %}danger{% endif %}">{{ user.is_active }}</span>
              
            </div>
        </div>
    </div> -->
    {% endfor %}
    {% endif %}
    <!--{% if page_obj.has_other_pages %}
    <nav aria-label="Page navigation" class="pb-3 pt-2">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
          {% endif %}
          {% for p in page_obj.paginator.page_range %}
          {% if page_obj.number == p %}
          <li class="page-item"><a class="page-link active" href="?page={{ p }}">{{ p }}</a></li>
          {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
          <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
          {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
          {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% for index, request in requests %}
<div class="modal fade" id="modal{{ request.id }}" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="ModalLabel">Request {{ index }}</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body border">
        <b>From:</b> {{ request.start_date|date:'F d, Y' }}<br>
        <b>Till:</b> {{ request.finish_date|date:'F d, Y' }}<br>
        <b>Leave Type:</b> {{ request.leave_type }}<br>
        <b>Reason:</b> <br>{% if request.reason %}{{ request.reason }}<br>{% endif %}
        <span class="badge text-bg-{% if request.status == statuses.Waiting %}primary{% elif request.status == statuses.Approved %}success{% else %}danger{% endif %}">{{ request.get_status_display }}</span>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Got it</button>
      </div>
    </div>
  </div>
</div>
{% endfor %} -->
{% endblock content %}

vacation_management_app/templates/vacation_management_app/vacation_request.html
{% extends 'vacation_management_app/base.html' %}
{% block content %}
<div class="container d-flex justify-content-center align-items-center flex-column" style="height: inherit;">
    <div class="col-10 col-sm-6 col-md-5">{% include 'vacation_management_app/messages.html' %}</div>
    {% if unavalaible and not messages %}
    <div class="alert col-10 col-sm-6 col-md-5 alert-warning alert-dismissible fade show" role="alert">
        <strong>Attention!</strong> Unfortunately, your current status is <b>Viewer</b>, so you cannot send any requests, ask the administrator to change your status
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    <form class="col-10 col-sm-6 col-md-5"{% if unavalaible %}{% else %} method="POST"{% endif %}>
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_start_date" class="form-label mb-1">Start date:</label>
            <input type="date" name="start_date" class="form-control" required id="id_start_date">
        </div>
        <div class="mb-3">
            <label for="id_finish_date" class="form-label mb-1">Finish date:</label>
            <input type="date" name="finish_date" class="form-control" required id="id_finish_date">
        </div>
        <div class="mb-3">
            <label for="id_leave_type" class="form-label mb-1">Leave Type:</label><br>
            <select name="leave_type" id="id_leave_type">
                <option value="">---------</option>

                <option value="Casual" selected="">Casual</option>
              
                <option value="Medical" >Medical</option>
              
                <option value="Optional">Optional</option>

                <option value="Regional">Regional</option>
              
              </select>
        </div>
        <div class="mb-3">
            <label for="id_reason" class="form-label mb-1">Leave Reason:</label>
            <textarea name="reason" rows="5" maxlength="1000" class="form-control" id="id_reason"></textarea>
        </div>
        {% if unavalaible %}<button class="btn btn-secondary" disabled >Submit</button>{% else %}<button type="submit" class="btn btn-primary">Submit</button>{% endif %}
    </form>
</div>
{% endblock content %}